name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Check PR author
      id: check-author
      run: |
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is_dependabot=true" >> $GITHUB_OUTPUT
        else
          echo "is_dependabot=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout code
      if: steps.check-author.outputs.is_dependabot == 'true'
      uses: actions/checkout@v4

    - name: Setup Node.js
      if: steps.check-author.outputs.is_dependabot == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      if: steps.check-author.outputs.is_dependabot == 'true'
      run: npm ci

    - name: Run lint
      if: steps.check-author.outputs.is_dependabot == 'true'
      run: npm run lint

    - name: Check if PR is safe to merge
      if: steps.check-author.outputs.is_dependabot == 'true'
      id: check-pr
      run: |
        # Check if this is a patch or minor update
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ "$PR_TITLE" =~ ^chore\(deps(-dev)?\):.*bump.*from.*to.* ]]; then
          echo "safe_to_merge=true" >> $GITHUB_OUTPUT
        else
          echo "safe_to_merge=false" >> $GITHUB_OUTPUT
        fi

    - name: Enable auto-merge
      if: steps.check-author.outputs.is_dependabot == 'true' && steps.check-pr.outputs.safe_to_merge == 'true'
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}